global:
  scrape_interval: "10s" # Как часто собирать метрики
  evaluation_interval: "10s" # Как часто вычислять правила агрегации и алертинга

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  
  - job_name: "auth"
    static_configs:
      - targets: ["auth:2112"]
    metrics_path: /metrics
  - job_name: "chat-server"
    static_configs:
      - targets: ["chat-server:2113"]
    metrics_path: /metrics
  - job_name: "web-gateway"
    static_configs:
      - targets: ["web-gateway:2114"]
    metrics_path: /metrics